version: '3.8'

services:
  app:
    build: .
    container_name: chat_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@127.0.0.1:3306/chat
      - SECRET_KEY=secret_#$%@@
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER_NAME: root
      MYSQL_DATABASE: chat
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
